### ISSUE TITLE
Error in make_dataset

### ISSUE THREAD

**Issue by halbersb** [fdtomasi/regain#22]
## Expected Behavior
New data set should be created

## Actual Behavior
An error occurred

## Steps to Reproduce the Problem

  1. pip install regain
  2. pip install all dependencies
  3. run Quickstart
  4. error in gaussian.py line 393: "assert (is_pos_def(theta_observed))"

![error message](https://user-images.githubusercontent.com/57631820/75264875-bc3f6a80-57f8-11ea-97db-d7ed7675e917.PNG)

**Comment by fdtomasi** [comment]
This should be fixed in #23 .
