### ISSUE TITLE
Datasets NoModuleFound Error

### ISSUE THREAD

**Issue by Vlasovets** [fdtomasi/regain#25]
Hello!

I have just found that it is not possible to generate synthetic data using your functionalities in `regain/datasets/base.py`

The reason is a recent sklearn update of datasets module, you might want to change line 36 in the file above as following `from sklearn.utils import Bunch`

I'm interested in your graphical lasso with latent variables, would be cool if you can check this issue.
Currently, I have the following error when try to reproduce your example:

`--------------------------------------------------------------------------
ModuleNotFoundError                      Traceback (most recent call last)
<ipython-input-10-c8863a4ca7fc> in <module>
----> 1 from regain.datasets import datasets

~/opt/anaconda3/envs/gglasso/lib/python3.8/site-packages/regain/datasets/__init__.py in <module>
     28 # OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
     29 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---> 30 from .base import make_dataset

~/opt/anaconda3/envs/gglasso/lib/python3.8/site-packages/regain/datasets/base.py in <module>
     34 
     35 import numpy as np
---> 36 from sklearn.datasets.base import Bunch
     37 
     38 from .gaussian import (

ModuleNotFoundError: No module named 'sklearn.datasets.base'`

**Comment by fdtomasi** [comment]
Thank you, this should be fixed now. It was already fixed in the `develop` branch, I just merged the PR for that.
