### ISSUE TITLE
Attempting to import regain.linear_model raises error

### ISSUE THREAD

**Issue by DManowitz** [fdtomasi/regain#29]
**Describe the bug**
Attempting to import regain.linear_model raises error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\regain\linear_model\__init__.py", line 31, in <module>
    from .group_lasso_overlap_ import GroupLassoOverlap, GroupLassoOverlapClassifier
  File "...\lib\site-packages\regain\linear_model\group_lasso_overlap_.py", line 39, in <module>
    from sklearn.linear_model.base import LinearClassifierMixin, LinearModel, _pre_fit
ModuleNotFoundError: No module named 'sklearn.linear_model.base'
```

**To Reproduce**
Install regain and scikit-learn >=1.0.2 (or possibly earlier version)
Attempt to `import regain.linear_model`

**Expected behavior**
No error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: regain v0.3.3; scikit-learn v1.0.2

**Comment by fdtomasi** [comment]
Thank you for raising this. I updated scikit-learn and relative imports. Feel free to re-open in case you still have issues.

**Comment by fdtomasi** [comment]
I did not look into the specifics of the version, sorry. I am not sure when scikit-learn introduced the new module names (to be fair they change them pretty often) so I just used the latest version. This library does not use features of the new Python 3.8+ so would still work with previous versions. I can look edit the requirements to require scikit-learn >= 1.0 which should fix this!

**Comment by fdtomasi** [comment]
I added the requirements to include `sklearn>=1.0` in v0.3.6. That should work -- they changed the name from `linear_model.base` to `linear_model._base` from this version.
