### ISSUE TITLE
Module 'collections' has no attribute 'Mapping' error with Python 3.10.10

### ISSUE THREAD

**Issue by ekat92** [fdtomasi/regain#39]
Attempting to import GraphicalLasso (or any other module) from regain raises error:

from GL import GraphicalLasso
Results in the **Module 'collections' has no attribute 'Mapping' error** as in the screenshot below:

**Screenshots**
![image](https://github.com/fdtomasi/regain/assets/59748687/a0cbc9d8-4826-4e1e-8e99-1e4cb7f175ec)

Getting this error when executing in AWS SageMaker notebook (Amazon Linux 2) with Python 3.10.10 | packaged by conda-forge

**Comment by ekat92** [comment]
Thanks, the previous warning is fixed, but now I am getting a different one when importing GraphicalLasso (this error is actually now raised when Python 3.8 as well):
-- from GL import GraphicalLasso
**ImportError: cannot import name 'soft_thresholding_od' from 'regain.prox' (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/regain/prox.py)**

![image](https://github.com/fdtomasi/regain/assets/59748687/415d7f33-2c05-450e-b660-1d8b04e4b9b3)

**Comment by fdtomasi** [comment]
Yes with the new `regain` version 0.3.9 I merged few changes which include an updated `prox` module. The `soft_thresholding_od` function in particular has been renamed to `soft_thresholding_off_diagonal` and it is able to work with Tensors, replacing the `_soft_thresholding_od_2d ` function as well.
To fix, update the import to `from regain.prox import soft_thresholding_off_diagonal`.

Feel free to reopen in case you encounter any other issue. Thanks!
